spring.application.name=letsplay
spring.mongodb.uri=mongodb://localhost:27017/letsplay
server.port=8080

server.ssl.enabled=true
server.ssl.key-store=classpath:letsplay.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=letsplay