spring.application.name=letsplay
spring.mongodb.uri=${MONGO_URL}
server.port=8080

jwt.secret=${JWT_SECRET}

server.ssl.enabled=true
server.ssl.key-store=${SSL_FILE}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=letsplay

admin.name=${ADMIN_NAME}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}